### ISSUE TITLE
Improving the attributions to the original RDM kit (avoiding confusions)

### ISSUE THREAD

**Issue by nsunami** [eur-nl/erim-research-toolbox#13]
In a video meeting, we identified that the footer language may imply that the original RDM kit team may be contributing to the content. We want to avoid that confusion.

To resolve this, the following edits have been suggested:

1. Change the footer language, and remove the CONVERGENCE, and make it clear that this is a fork/independent derivative maintained by the ERIM/EUR team

<img width="540" alt="image" src="https://user-images.githubusercontent.com/17035406/218469820-68a67ef0-d2be-43f9-b7b1-4534f2448470.png">

2. Remove the original RDM kit team from the contributors

<img width="279" alt="image" src="https://user-images.githubusercontent.com/17035406/218469663-7d81a05b-2d10-4ac2-ac93-e2402535b2ff.png">

3. Consider changing the name/branding from RDM kit to something else to avoid confusion

(Thanks, @bedroesb, for relaying the info! Let me know if I missed something!)

**Comment by bedroesb** [comment]
@nsunami Dou you know what the plans are about this? If you need any help please let me know!

**Comment by nsunami** [comment]
@bedroesb I just merged a PR addressing these #14. If you think I missed something, please feel free to open another issue!

**Comment by bedroesb** [comment]
@nsunami thanks a lot! We are still in the process in deciding how people should attribute, but I will get back to you when we have something concrete. Small remark: it is RDMkit and not RDMToolkit :)
