### ISSUE TITLE
Updating page: Planning

### ISSUE THREAD

**Issue by LizGuzRam** [eur-nl/erim-research-toolbox#18]
Updates on the page Planning to reflect the information needed for EUR researchers

**Comment by LizGuzRam** [comment]
Hey @nsunami it will be great if you can double check my edits to this page :)

**Comment by LizGuzRam** [comment]
@nsunami I realized there are more changes needed, I will assign you to this once this is ready for you to revise

**Comment by nsunami** [comment]
@LizGuzRam : Sure! Maybe it's better if you create a Pull Request based on your branch [18-updating-page-planning](https://github.com/eur-nl/erim-research-toolbox/tree/18-updating-page-planning) and I provide my review in the PR?
