### ISSUE TITLE
Consider changing the icon for the collecting phase

### ISSUE THREAD

**Issue by LizGuzRam** [eur-nl/erim-research-toolbox#22]
Could it be possible to change the icon for the collecting phase

**Comment by nsunami** [comment]
Currently, the icon for the collecting phase is very sciency- 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/17035406/235148488-a4616ae0-2ab3-45ed-b873-3bf65410759f.png">

We may want to consider changing this. 

It may be better if we use a consistent icon set.

Ideas:
 1. Carbon - https://carbondesignsystem.com/guidelines/icons/library
 2. bootstrap icons - https://icons.getbootstrap.com/
