### ISSUE TITLE
Page links inside the pages don't work for all pages

### ISSUE THREAD

**Issue by LizGuzRam** [eur-nl/erim-research-toolbox#50]
In some of the pages, the links that are at the beginning of the page do not seem to send you the part where the information resides (inside the same page), but it does work for other pages. 
![links](https://github.com/eur-nl/erim-research-toolbox/assets/85296852/1d2a87dc-7d06-46bc-b076-d7ca3fb9747b)

**Comment by LizGuzRam** [comment]
I just realized they do not work on any of the pages inside the ERIM environment in Firefox, but they seem to work in the Deployed version online

**Comment by LizGuzRam** [comment]
I don't know what is causing this tho...

**Comment by nsunami** [comment]
I was able to replicate this issue in the TYPO3 test environment: 

https://github.com/eur-nl/erim-research-toolbox/assets/17035406/70cab39a-7992-4d8b-8e48-03c889c8a8c0

This has something to do with using iframe, but other than that, I don't have a clue. It may be tricky to fix.

**Comment by LizGuzRam** [comment]
Oh shame! no worries, this is definitely not a high priority issue! we can live without it :)
