### ISSUE TITLE
Creating a page for training resources

### ISSUE THREAD

**Issue by nsunami** [eur-nl/erim-research-toolbox#62]
Under Planning > Data Management Planning, we planned to have RDM Training page (e.g., Scientific integrity course).

We want to have a page that lists our training resources.

**Comment by LizGuzRam** [comment]
Training page, links to add: 
1. Watch your research data 
2. EUR Coffee Data Breaks 
3. Check: https://my.eur.nl/en/eur-employee/research/research-services/research-data-management/rdm-workshops
